# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Utkarsh Saxena
title: Software Engineer
email: utkarshsaxena2012@gmail.com
website: https://github.com/UtkarshSaxenautk

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: UtkarshSaxenautk
stackoverflow_username: "19090939"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username:
linkedin_username: utkarsh-saxena-5a9034201
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: leetcode
    icon: fab fa-rectangle-terminal
    url: https://leetcode.com/usutk/
  - title: codechef
    url: https://www.codechef.com/users/utk_2003
  - title: codeforces
    url: https://codeforces.com/profile/Utk__03
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/utk_new.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Utkarsh, B.Tech Computer Science Engineering Student. Have good coding skills in Golang,Node js and Java. A passionate professional with great interpersonal and communication skills.
  Key Skills:
  1. Go
  2. Java
  3. NodeJs
  4. React
  5. C++
  6. Git 
  7. Data Structure and Algorithms
  8. Jira
  9. MongoDB
  10. MySQL

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Chat Room
        link: https://github.com/UtkarshSaxenautk/Chat_Room
        description: | # this will include new lines to allow paragraphs
          Simple Chat room application built using NodeJS and ReactJS with socket io and mongoDB as database.
          Having functionality of creating new rooms and joining rooms with user login and signup feature.
      - layout: top-middle
        title: Auth Service
        link: https://github.com/UtkarshSaxenautk/GoAuthService
        description: | # this will include new lines to allow paragraphs
          Authentication Microservice with exposed api to be used as pkg to use authentication service and using sendGrid Api to send mails.
      - layout: top-middle
        title: Electric Bill Optimizer
        link: https://github.com/UtkarshSaxenautk/Electric-Bill-Optimizer-HTM3.0
        description: | # this will include new lines to allow paragraphs
          A Mern based web app for optimizing your monthly bill according to expected bill and practical bill with twilio integration for notifications and hourly alerts.
      - layout: top-middle
        title: Hotel Booking Site
        link: https://github.com/UtkarshSaxenautk/Booking-Site
        description: | # this will include new lines to allow paragraphs
          A Modern Web app based on golang and its templates to book hotels and rooms according to location using PostgreSQL database
                                      with mailing functionality.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: myMandap
        link: https://mymandap.in/
        # link_text: boringcompany.com
        sub_title: Software Engineer Intern
        caption: August 2022 - Present
        description: | # this will include new lines to allow paragraphs
          * Writing Microservices in Golang for RabbitLoader(https://rabbitloader.com/)
          * Api making in Golang
          * Unit testing 
          * Docker images and compose files
      - layout: left
        title: Wizwack
        link: https://wizwack.in/
        # link_text: boringcompany.com
        sub_title: Full Stack Developer Intern
        caption: May 2022 - August 2022
        description: | # this will include new lines to allow paragraphs
          * Writing features for StarHunt Game on : Wizwack(https://wizwack.in/)
          * Bug fixing 
          * Working on payment service(Cashfree Sdk)
          * APi making and bulk testing

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: I.K. Gujral Punjab Technical University
        caption: 2020 - 2024
        sub_title: Bachelor of Technology(Computer Science Engineering)

        description: | # this will include new lines to allow paragraphs
          Average grade: 8.86
      - layout: left
        title: St. Xavier's Senior Secondary School
        caption: 2018-2020
        sub_title: 10+2(XII)

        description: | # this will include new lines to allow paragraphs
          Percentage : 95.65
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Gaming(Cricket)
      - Exploring Animals Life
      - Music Production

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
